src/dm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path('', include("home.urls")),
    path('contact', include("contact.urls")),
    path('products/', include("products.urls")),
    path('chat/', include("chat.urls")),
    path('questions/', include("questions.urls")),
    path('opening/', include("opening.urls")),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))

src/home/urls.py
# Django
from django.urls import path

# Own
from .views import HomeView


app_name = "home"
urlpatterns = [
    path('', HomeView, name="home")

]

src/products/api/urls.py
from django.urls import path

from .views import get_categories, get_products_view, get_recommended_products_view


app_name = 'api'
urlpatterns = [
    path('categories/', get_categories, name="get-categories"),
    path('products/', get_products_view, name="get-products"),
    path(
        'recommended-products/<int:product_id>',
        get_recommended_products_view,
        name="get-recommended-products"),
]

src/products/urls.py
from django.urls import path, include
from django.conf import settings

from .views import product_view


app_name = "products"
urlpatterns = [
    path('<int:product_id>', product_view, name="product"),
    path(f'api/{settings.API_VERSION}/', include('products.api.urls'))
]

src/products/models.py
import os

from django.db import models


def upload_to(product_code: int) -> str:
    code = str(product_code)
    upload_path = os.path.join('img', 'products', f'{code}/')
    return upload_path


def upload_img_product(instance, filename):
    product_code = instance.code
    upload_path = upload_to(product_code)
    return os.path.join(upload_path, filename)


class Brand(models.Model):

    name = models.CharField(max_length=50)

    def save(self, *args, **kwargs):
        self.name = self.name.upper()
        super(__class__, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class Category(models.Model):

    name = models.CharField(max_length=30)
    num_products = models.PositiveSmallIntegerField("Number of products")
    enable = models.BooleanField(default=False)

    class Meta:
        indexes = [
            models.Index(fields=['enable'], name='category_enable_idx')
        ]

    def decrease_num_products(self):
        self.num_products -= 1
        if self.num_products == 0:
            self.enable = False
        self.save()

    def increase_num_products(self):
        self.num_products += 1
        if self.num_products == 0:
            self.enable = True
        self.save()

    def save(self, *args, **kwargs):
        self.name = self.name.lower().capitalize()
        super(__class__, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class Product(models.Model):

    categories = models.ManyToManyField(Category, related_name='products')
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE,
                              null=True, blank=True)

    code = models.PositiveSmallIntegerField()
    name = models.CharField(max_length=50)
    normalized_name = models.CharField(max_length=50, blank=True)
    description = models.TextField(null=True, blank=True)
    stock = models.SmallIntegerField(null=True)
    in_stock = models.BooleanField(default=True)
    price = models.DecimalField(max_digits=7, decimal_places=2)

    img = models.ImageField(upload_to=upload_img_product, null=True)
    img_webp = models.ImageField(null=True, blank=True)
    img_small_webp = models.ImageField(null=True, blank=True)
    optimize_image = models.BooleanField(default=False)

    class Meta:
        indexes = [
            models.Index(fields=['code'], name='product_code_idx')
        ]

    def __str__(self):
        return self.name

src/products/utils/models.py
from pathlib import Path
from abc import ABC, abstractmethod

from django.core.files.images import ImageFile
from django.conf import settings


class IConvertor(ABC):

    @abstractmethod
    def save_resized_image(self, width: int = 376) -> str:
        pass

    @abstractmethod
    def save_webp_image(self) -> str:
        pass


class ImageConvertor(IConvertor):

    SMALL_PREFIX = 'small_'

    def __init__(self, img: ImageFile, upload_path: str):
        self.img = img
        self.upload_path = upload_path
        self.media_dir = settings.BASE_DIR / settings.MEDIA_FOLDER
        self.full_upload_path = self.media_dir / self.upload_path

    def save_resized_image(self, width: int = 376) -> str:
        # 376px min expected sized obtained from lighthouse
        self.__resize(width)
        name = self._get_name_of_resized()
        self._save_in_media_folder(name)
        relative_path = self._get_relative_path(name)
        return relative_path

    def save_webp_image(self) -> str:
        name = self._get_new_file_name()
        self._save_in_media_folder(name)
        relative_path = self._get_relative_path(name)
        return relative_path

    def _save_in_media_folder(self, name: str, format: str = None) -> None:
        full_path = self.full_upload_path / name
        self.img.save(full_path, format=format)

    def _get_relative_path(self, name: str) -> str:
        relative_path = self.upload_path + name
        return relative_path

    def __resize(self, width: int) -> None:
        r = self.__get_ratio()
        self.img.thumbnail((width, int(width / r)))

    def __get_ratio(self) -> float:
        w, h = self.img.size
        ratio = w / h
        return ratio

    def _get_name_of_resized(self) -> str:
        prefix = ImageConvertor.SMALL_PREFIX
        name = self._get_new_file_name(prefix)
        return name

    def _get_new_file_name(self, prefix='') -> str:
        file_name = Path(self.img.filename).stem
        return f'{prefix}{file_name}.webp'


class ImageConvertorFactory:

    @staticmethod
    def get_convertor(img: ImageFile, upload_path: str) -> IConvertor:
        return ImageConvertor(img, upload_path)

src/products/api/views.py
from django.db.models import Q
from django.views.decorators.http import require_http_methods
from django.db.models.query import QuerySet
from django.core.paginator import Paginator
from django.urls import reverse
from django.conf import settings
from django.core.cache import cache

from utils.normalize import normalize_query_string
from utils.response import ResponseJsonBuilder
from utils.cache.constants import CACHE_KEY_MOD_PRODUCTS
from services.recommendations import get_recommended_products
from products.models import Product, Category
from .serializers import ProductListSerializer
from .utils import get_limit


@require_http_methods(["GET"])
def get_categories(request):
    res_builder = ResponseJsonBuilder()
    categories = Category.objects.filter(enable=True)
    res_builder.obj = categories
    return res_builder.get_response()


@require_http_methods(["GET"])
def get_products_view(request):
    res_builder = ResponseJsonBuilder()
    category_id = request.GET.get('category', False)
    query = request.GET.get('query', False)

    if category_id:
        products = search_by_category(category_id)
    elif query:
        products = search_by_words(query)
    else:
        products = cache.get_or_set(CACHE_KEY_MOD_PRODUCTS, Product.objects.all())

    products, pagination = get_pagination(request.GET, products)
    products_list = convert_to_list(products)
    res_builder.obj = {
        'products': products_list,
        'pagination': pagination
    }
    return res_builder.get_response()


@require_http_methods(["GET"])
def get_recommended_products_view(request, product_id: int):
    res_builder = ResponseJsonBuilder()
    limit = get_limit(request.GET)
    products = get_recommended_products(product_id, limit)
    data = ProductListSerializer(products, many=True).data
    res_builder.obj = data
    return res_builder.get_response()


def search_by_category(category_id: str) -> QuerySet:
    try:
        c = Category.objects.get(id=category_id)
    except (Category.DoesNotExist, ValueError):
        products = Product.objects.all()
    else:
        products = c.products.all()
    return products


def search_by_words(query: str) -> QuerySet:
    query = normalize_query_string(query)
    products = Product.objects.filter(
        Q(normalized_name__icontains=query) | Q(code__icontains=query)
    )
    return products


def convert_to_list(products: QuerySet) -> list[dict]:
    url = settings.DOMAIN
    product_list = []
    for product in products:
        item = {
            'id': product.id,
            'name': product.name,
            'normalizedName': product.normalized_name,
            'price': product.price,
            'code': product.code,
            'img': {
                'url': f'{url}{product.img_small_webp.url}',
                'width': product.img_small_webp.width,
                'height': product.img_small_webp.height
            },
            'productLink': reverse('products:product', kwargs={'product_id': product.id})
        }
        product_list.append(item)
    return product_list


def get_pagination(request_get: dict, query: QuerySet) -> tuple[QuerySet, dict]:
    page_param = request_get.get('page', 1)
    items_param = request_get.get('items', 12)
    paginator = Paginator(query, items_param)
    page = paginator.page(page_param)
    pagination = {
        'page': page_param,
        'hasPrevious': page.has_previous(),
        'hasNext': page.has_next(),
        'numPages': paginator.num_pages
    }
    return page.object_list, pagination

src/products/utils/views.py
from django.db.models import Q

from products.models import Product


# TODO: Cache
def get_recommended_products_of(
    product: Product,
    size: int = 4
) -> list[Product]:
    excluded_id = product.id
    categories = product.categories.filter(enable=True)
    recommended = set()

    for c in categories:
        recommended.update(c.product_set.all().exclude(id=excluded_id))

    if len(recommended) < size:
        excluded_ids = _get_excluded_ids(recommended, excluded_id)
        amount = size - len(recommended)
        extra_products = _get_extra_products(excluded_ids, amount)
        recommended.update(extra_products)

    return list(recommended)[:size]


def _get_extra_products(excluded_ids: list[int], amount: int) -> list[Product]:
    extra_products = Product.objects.filter(~Q(id__in=excluded_ids))
    return extra_products[:amount]


def _get_excluded_ids(recommended: list[Product], excluded_id: int) -> list[int]:
    excluded_ids = [r.id for r in recommended]
    excluded_ids.append(excluded_id)
    return excluded_ids

src/products/views.py
from django.http import Http404
from django.shortcuts import render
from django.views.decorators.http import require_http_methods

from .models import Product


@require_http_methods(["GET"])
def product_view(request, product_id):

    try:
        product = Product.objects.get(id=product_id)
    except Product.DoesNotExist:
        raise Http404("Product Not Found")
    else:
        context = {
            "product": product,
        }
    return render(request, "products/product.html", context)

src/templates/products/product.html
{% extends 'base.html' %}

{% load static %}

{% block preload %}
<link rel="preload" href="{% static 'css/products/products.css' %}" as="style">
<link rel="preload" href="{% static 'css/products/product.css' %}" as="style">
<link rel="preload" href="{% static 'css/products/questions.css' %}" as="style">
{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/products/products.css' %}">
<link rel="stylesheet" href="{% static 'css/products/product.css' %}">
<link rel="stylesheet" href="{% static 'css/products/questions.css' %}">
{% endblock %}

{% block content %}
<div class="container">
   <div class="row my-4">

      <div class="col-12">
         <a href="{% url 'home:home'%}#products" class="btn btn-link"><i class="bi bi-arrow-left left"></i>Home</a>
      </div>
      
      <div class="col-12 main-product" data-product-id="{{ product.id }}">
         <div class="row">
            <div class="col-12 col-md-8 product-img">
               <img src="{{product.img_webp.url}}" alt="Product Image" loading="lazy">
            </div>
            <div class="col-12 col-md-4 product-detail">
               <div class="row product-title">
                  <div class="col-12">
                     <h2>{{product.name}}</h2>
                  </div>
               </div>
               <div class="row product-info">
                  <div class="col-6 price">
                     <p class="text-success text-left">$ {{product.price}}</p>
                  </div>
                  <div class="col-6 availability">
                     <p class="text-muted text-right">{% if product.in_stock %}Stock{% else %}Out of stock{% endif %}
                     </p>
                  </div>
               </div>
               <div class="row product-description">
                  <div class="col-12">
                     <p>{{product.description}}</p>
                  </div>
                  <div class="col-12 code" data-code="{{product.code}}">
                     <p class="text-muted text-left">Code: {{product.code}}</p>
                  </div>
               </div>
               <div class="row product-consult">
                  <div class="col-12">
                     <button type="button" class="btn btn-success d-block w-100">
                        Ask <i class="bi bi-whatsapp"></i>
                     </button>
                     <div class="product-questions d-none">
                        <ul></ul>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>

      <div class="col-12 recommendations">
         <div class="row my-4">
            <div class="col-12">
               <p class="text-center">Products may you be interested in:</p>
            </div>
         </div>

         <div class="row products">

            <div class="col-12 products-loader">
               <img src="/static/img/loader.svg" alt="Loading Image">
               <span class="loading-text">Loading related products...</span>
            </div>

            <div class="col-12 products-list d-none">
               <div class="row justify-content-center">
               </div>
            </div>
         </div>

         <template id="template-product-card">
            <a class="col-lg-3 col-sm-6 my-1 px-1 .product" href="">
               <div class="card product">
                  <div class="product-header">
                     <img class="card-img-top custom-img" src="" alt="Image" loading="lazy">
                     <div class="price">
                        <span></span>
                     </div>
                  </div>

                  <div class="product-title">
                     <div class="name">
                        <span></span>
                     </div>
                  </div>
               </div>
            </a>
         </template>
      </div>

   </div>
</div>

<div class="d-none" id="questions-data">
   <input type="hidden" class="url" value="{% url 'questions:api:questions' %}">
   {% csrf_token %}
</div>

{% endblock %} 

{% block script %}
<script async src="{% static 'js/products/questions.js'%}" type="module"></script>
<script async src="{% static 'js/products/recommendedProducts.js'%}" type="module"></script>
{% endblock %}

src/templates/products/products.html
{% load static %}

<div class="row products" id="products">

   <div class="col-12">
      <h2 class="text-center">Our products:</h2>
   </div>

   <div class="col-12 products-search">
      {% include 'products/search.html' %}
   </div>

   <div class="col-12 products-list">
      <div class="row justify-content-center">
      </div>
   </div>

   

   <div class="search-not-found col-12 d-none" id="search-not-found">
      <p class="text-center">We did not find any results.</p>
   </div>

   <div class="col-12 loader" id="products-loader">
      <img src="{% static 'img/loader.svg' %}" alt="Load products">
   </div>

   {% include 'pagination.html' %}
   
   <div class="col-12 products-info d-none" id="products-data">
      <input type="text" class="url-get-products" value="{% url 'products:api:get-products' %}">
   </div>

   <template id="item-product">
      <div class="col-lg-3 col-sm-6 my-1 px-1">
         <div class="card product">

            <div class="product-header">
               <img class="card-img-top custom-img" src="" alt="Image" loading="lazy">
               <div class="price">
                  <span></span>
               </div>
               <div class="code d-none">
                  <span></span>
               </div>
            </div>

            <div class="product-title">
               <div class="name">
                  <span></span>
               </div>
            </div>
         </div>
      </div>
   </template>
</div>

src/templates/products/search.html
<div class="row justify-content-center search" id="search">

    <div class="col-12 col-md-8 search-container">
        <div class="row search-relative-container">
            <div class="col-10 col-sm-11 p-0 h-100">
                <input type="text" name="q" id="searchInput" class="search-input" placeholder="Search" value=""
                    autocomplete="off">
            </div>
            <div class="col-2 col-sm-1 p-0 h-100">
                <button type="button" class="search-btn" id="searchBtn" aria-label="search"><i class="bi bi-search"></i></button>
            </div>
            <div class="col-12 search-result-list d-none">
                <ul></ul>
            </div>
        </div>
    </div>

    <div class="col-12 pl-0 pr-0 search-categories" id="categories">
        <ul class="categories-list">
            <li class="search-category" data-id="0">
                <span class="badge badge-primary custom-span-category">All</span>
            </li>
            {% for c in categories %}
            <li class="search-category" data-id="{{c.id}}">
                <span class="badge badge-primary custom-span-category">{{c.name}}</span>
            </li>
            {% endfor %}
        </ul>
    </div>

    <div class="d-none" id="categories-data">
        <input type="url" class="get-products" value="{% url 'products:api:get-products' %}">
    </div>
    
</div>